service: teamtask

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ca-central-1

functions:
  createTask: 
    handler: src/functions/createTask.handle
    events:
      - http:
          path: /create-task/{user_id}
          method: POST
          cors: true
  listTasksByUser:
    handler: src/functions/listTasksByUser.handle
    events:
      - http:
          path: /list-tasks/{user_id}
          method: GET
          cors: true
  finishTask:
    handler: src/functions/finishTask.handle
    events:
      - http:
          path: /finish-task/{user_id}
          method: POST
          cors: true

resources:
  Resources:
    dbCertificateUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S

        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
